services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: capas-flask:compose
    container_name: web-capas
    ports:
      - "5000:5000"
    environment:
      - SALUDO=Hola desde Compose
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:5000/', timeout=2)"]
      interval: 30s
      timeout: 3s
      retries: 3
